### ISSUE TITLE
[Sugestão] - Padronização da pasta do projeto

### ISSUE THREAD

**Issue by mariotlemes** [LABORA-INF-UFG/SBrT2020-Minicurso1#2]
Nos tutoriais **my5G-core Setup** e **Setting up development environment** o projeto é clonado para ~/my5gcore. Já em **Initial registratrion procedure**, subseção **Installing required tools** - item 2: **Building UE-IoT-non3GPP**, o UE é clonado para a pasta ~/my5g-core, ocasionando erro ao seguir o tutorial pois o nome da pasta é diferente do tutorial inicial de _setup_ e configuração do ambiente. É interessante que o nome da pasta do projeto seja padronizado em todos os tutoriais.

Obs:. Não realizei _pull request_ pois creio que essa decisão (my5core ou my5g-core) deve ser do grupo, além do que, dependendo do que for abordado, algumas imagens terão que ser alteradas.

**Comment by jplobianco** [comment]
@rogerio-silva repassando pra vc. O padrão seria todos referenciarem my5G-core

**Comment by antoniocojr** [comment]
Obrigado @mariotlemes pela contribuição. O padrão é my5G-core. Isso tem impacto na continuidade do seu trabalho? Ou você conseguiu seguir normalmente?

**Comment by mariotlemes** [comment]
> Obrigado @mariotlemes pela contribuição. O padrão é my5G-core. Isso tem impacto na continuidade do seu trabalho? Ou você conseguiu seguir normalmente?

Consegui seguir normalmente. Percebi que a compilação do UE-IoT-non3GPP deu problema devido ao nome errado da pasta. De qualquer forma isso pode ser impeditivo para alguém, sendo indicado a padronização.

Em relação a possíveis problemas em relação a continuidade, outro ponto talvez seja interessante comentar: a necessidade de realizar o comando **sudo make install** referente ao módulo gtp5g - dentro de ~/gtp5g -  toda vez que a máquina é reiniciada. Percebi que ao reiniciar a VM é necessário rodar esses comando novamente para que o protocolo de tunelamento seja encontrado.

Em dois momentos distintos precisei realizar a tarefa descrita para continuar com o tutorial. Havia desligado a VM e precisei refazer este passo que consta lá no primeiro tutorial. Talvez isso seja um problema maior do que o nome errado da pasta.

Creio que a criação de um _daemon_ para inicialização junto com boot do Sistema Operacional, logo depois da instalação dessa lib resolveria o problema e, ao mesmo tempo, seria transparente para o usuário que esteja seguindo o tutorial.

**Comment by jplobianco** [comment]
Referências atualizadas para my5G-core.

@mariotlemes Em relação ao daemon, não precisa, uma vez que o módulo é instalado ele é carregado juntamente com o linux durante a inicialização (é inserido no /etc/modules). No seu caso, deve ter sido devido à mudança de nome da pasta my5Gcore para my5G-core e por isso acabava não sendo encontrado.
