### ISSUE TITLE
Problema ao importar workspace - GoLand IDE

### ISSUE THREAD

**Issue by mariotlemes** [LABORA-INF-UFG/SBrT2020-Minicurso1#4]
Localização:
 **Initial registratrion procedure** -> **Setting-up environment** -> **Importing GoLand IDE workspace**

Reprodução do erro:
A pasta oculta .idea é criada, porém o passo seguinte para criar o backup do arquivo workspace.xml dá erro pois não existe o arquivo na pasta recém criada. O comando seguinte copia o workspace de ~/my5G-core para .idea corretamente, contudo não consigo ter acesso ao workspace importado no goland.

Conclusão: 
O workspace com os breakpoints e configuração de execução não é importado para o goland.

Como resolver?

**Comment by jplobianco** [comment]
@mariotlemes Fizemos uma atualização. Tente novamente essa parte do tutorial.

**Comment by mariotlemes** [comment]
> @mariotlemes Fizemos uma atualização. Tente novamente essa parte do tutorial.

@jplobianco ainda sem sucesso.

Ao criar e executar o runConfigurations, o que aparece importado para o goland, no meu caso, é o ambiente **"TestVersion/VERSION_not_specified in free5gc/src/ausf/version"**

**Comment by jplobianco** [comment]
Tente essa solução aqui:

```bash
cd ~/my5G-core
rm -rf workspace.xml*
rm -rf runConfigurations.tar.gz*
rm -rf .idea/runConfigurations
wget -q https://raw.githubusercontent.com/LABORA-INF-UFG/SBrT2020-Minicurso1/master/media/workspace.xml
mkdir .idea
mv -f .idea/workspace.xml .idea/workspace.xml.orig
cp workspace.xml  .idea/    
#mkdir .idea/runConfigurations
wget -q https://raw.githubusercontent.com/LABORA-INF-UFG/SBrT2020-Minicurso1/master/media/runConfigurations.tar.gz
tar xvf runConfigurations.tar.gz -C .idea/
```

**Comment by mariotlemes** [comment]
> Tente essa solução aqui:
> 
> ```shell
> cd ~/my5G-core
> rm -rf workspace.xml*
> rm -rf runConfigurations.tar.gz*
> rm -rf .idea/runConfigurations
> wget -q https://raw.githubusercontent.com/LABORA-INF-UFG/SBrT2020-Minicurso1/master/media/workspace.xml
> mkdir .idea
> mv -f .idea/workspace.xml .idea/workspace.xml.orig
> cp workspace.xml  .idea/    
> #mkdir .idea/runConfigurations
> wget -q https://raw.githubusercontent.com/LABORA-INF-UFG/SBrT2020-Minicurso1/master/media/runConfigurations.tar.gz
> tar xvf runConfigurations.tar.gz -C .idea/
> ```

Funcionou!
