### ISSUE TITLE
Breakpoints não são habilitados no goland

### ISSUE THREAD

**Issue by mariotlemes** [LABORA-INF-UFG/SBrT2020-Minicurso1#6]
A importação do workpace com os breakpoints aconteceu normalmente com a atualização do tutorial, porém ao disparar a trigger para inicialização do registro inicial do UE, o goland não responde, ou seja, não "para" no primeiro breakpoint.

Ao verificar o wireshark, as mensagens são capturadas até o ponto da imagem:

![Captura de Tela 2020-12-02 às 18 03 17](https://user-images.githubusercontent.com/11560302/100931483-5c819880-34c9-11eb-9bc0-3b0d40c90c29.png)

Como resolver?

**Comment by jplobianco** [comment]
Olá @mariotlemes 

É inviável para nós auxiliar cada um que tentar replicar o minicurso, você terá que investigar por conta própria.
Além disso, pela captura o procedimento de registro não foi realizado por completo.
Ao fim desse tutorial tem passos para limpar o ambiente, tente executá-los e depois realizar o tutorial novamente.
Uma sugestão é desabilitar o ufw caso o sistema utilizado possua:
```bash
sudo systemctl stop ufw
```
Boa sorte!

**Comment by mariotlemes** [comment]
@jplobianco 

Por algum motivo eu achei que o workspace importado seteria os breakpoints de forma automática na IDE. Ao inserir os breakpoints manualmente, consegui reproduzir e capturar as mensagens no wireshark.

De qualquer forma, obrigado.
