### ISSUE TITLE
comentário para o comando Docker

### ISSUE THREAD

**Issue by thiagogmta** [LABORA-INF-UFG/SBrT2020-Minicurso1#9]
Apenas um comentário:

precisei colocar o **sudo** antes do comando a baixo para que pudesse executar:

docker run --rm -v $(pwd):/local \
  openapitools/openapi-generator-cli generate \
  -i /local/TS29518_Namf_Communication.yaml \
  -g go --skip-validate-spec \
  -o /local/Namf_Communication/

**Comment by jplobianco** [comment]
Obrigado @thiagogmta 
Adicionado dead34f
